
[Network]
#type rpc or channel
Type="channel"
CAFile="ca.crt"
Key="sdk.key"
Cert="sdk.crt"
[[Network.Connection]]
NodeURL="127.0.0.1:20200"
GroupID=1
# [[Network.Connection]]
# NodeURL="127.0.0.1:20200"
# GroupID=2

[Account]
# only support PEM format for now
KeyFile="0xa.pem"

[Chain]
ChainID=1
SMCrypto=false

[log]
Path="./"
