[Network]
#type rpc or channel
Type="channel"
CAFile="./conf/ca.crt"
Cert="./conf/sdk.crt"
Key="./conf/sdk.key"
# if the certificate context is not empty, use it, otherwise read from the certificate file
# multi lines use triple quotes
CAContext=''''''
KeyContext=''''''
CertContext=''''''

[[Network.Connection]]
NodeURL="127.0.0.1:20200"
GroupID="group0"

[Account]
# only support PEM format for now
KeyFile=".ci/0x83309d045a19c44dc3722d15a6abd472f95866ac.pem"

[Chain]
ChainID="chain0"
SMCrypto=false

[log]
Path="./"
